#!/bin/bash

#CREAREMOS UNA FUNCION PARA QUE NOS MUESTRE EL MENSAJE DE AYUDA

ayuda() {
#EL COMANDO CAT NOS MUESTRA EL CONTENIDO DE UN FICHERO
#EN ESTE CASO ESTAMOS USANDO UN FICHERO MOMENTANEO CON EL
#NOMBRE DE AYUDA, EL CONTENIDO SE ENCUENTRA ENTRE LAS PALABRAS AYUDA
cat << AYUDA
SYNTAXIS DEL COMANDO
	$0 NOMBRE_01 [NOMBRE_02] ... [NOMBRE_N]
DESCRIPCION
	Imprime en pantalla "Hola NOMBRE_1, NOMBRE_2, ..., NOMBRE_N" por pantalla
CODIGOS DE RETORNO
	1: ERROR =>  Si el número de parámetros es menor que 1
AYUDA

}

#COMPROBAMOS SI ESQUE INGRESO AL MENOS INGRESO UN PARAMETRO

if [ $# -le 0 ]; then
	echo "Debes introducir mas de un parametro"
	#EJECUTAMOS LA FUNCION AYUDA EN CASO NO HAYA INTRODUCIDO PARAMETROS
	ayuda
	exit 1
fi

#CREAMOS LA VARIABLE MENSAJE Y LA CONCATENAMOS CON LOS DEMAS PARAMETROS
#IGUAL AL EJERCICIO ANTERIOR
MENSAJE="Hola "
PRIMERO=1

while [ -n "$1" ]; do
	if [ $PRIMERO -eq 1 ]; then
		MENSAJE="$MENSAJE $1"
		PRIMERO=0
	else
		MENSAJE="$MENSAJE, $1"
	fi
	
	shift
done

#IMPRIMIMOS MENSAJE
echo "$MENSAJE !"
