#!/bin/bash

#CREAREMOS UNA FUNCION PARA QUE NOS MUESTRE EL MENSAJE DE AYUDA

ayuda() {
#INSTRUCCION CAT PARA MOSTRAR EL MENSAJE DE AYUDA
cat << AYUDA
SYNTAXIS DEL COMANDO
	$0 NOMBRE_01 [NOMBRE_02] ... [NOMBRE_N]
DESCRIPCION
	Imprime en pantalla "Hola NOMBRE_1, NOMBRE_2, ..., NOMBRE_N" por pantalla
CODIGOS DE RETORNO
	1: ERROR =>  Si el número de parámetros es menor que 1
	2: ERROR =>  El usuario ingresado no esta conectado
AYUDA

}

#VERIFICAMOS QUE HAYA INGRESADO AL MENOS UN PARAMETRO

if [ $# -le 0 ]; then
	echo "Debes introducir mas de un parametro"
	ayuda
	exit 1
fi

#CREAMOS LA VARIABLE MENSAJE PARA CONCATENAR CON LOS PARAMETROS
MENSAJE="Hola "
PRIMERO=1

#RECORREMOS EL BUCLE PARA TRABAJAR CON CADA PARAMETRO
while [ -n "$1" ]; do
	
	#EN LA VARIABLE USUARIO CONECTADO UTILIZAMOS LA INSTRUCCIÓN WHO
	#ESTA INSTRUCCION NOS DEVUELVE LA LISTA DE LOS USUARIOS CONECTADOS
	#AL SISTEMA UTILIZANDO | USAMOS TUVERIAS LOS CUALES NOS LLEVA EL RESULTADO
	#DE LA INSTRUCCION WHO A LA INSTRUCION GREP QUE BUSCA EL PARAMETRO ACTUAL
	#EN LO QUE NOS DEVUELVE WHO
	USUARIO_CONECTADO=`who | grep $1`

	#VALIDAMOS SI EN LA VARIABLE USUARIO_CONECTADO ESTA VACIO
	#SI ESTA VACIO NO ENCONTRO AL USUARIO ENTONCES MOSTRAMOS
	#UN MENSAJE, LA AYUDA Y TERMINAMOS LA EJECUCION
	#CASO CONTRARIO LO CONCATENA A MENSAJE
	if [ -z "$USUARIO_CONECTADO" ]; then
		echo "El usuario $1 no esta conectado"
		ayuda
		exit 2
	fi
	if [ $PRIMERO -eq 1 ]; then
		MENSAJE="$MENSAJE $1"
		PRIMERO=0
	else
		MENSAJE="$MENSAJE, $1"
	fi
	
	#PASAMOS AL SIGUIENTE PARAMETRO
	shift
done

#POR ULTIMO SI TODO HA SALIDO BIEN MOSTRAMOS LA VARIABLE MENSAJE
echo "$MENSAJE !"
